name: pgmorl
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py37_0
  - cpuonly=1.0=0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.13=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2020.0=166
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - patchelf=0.10=he6710b0_0
  - pcre=8.43=he6710b0_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h7b6447c_0
  - py-opencv=3.4.2=py37hb342d67_1
  - python=3.7.6=h0371630_2
  - pytorch=1.4.0=py3.7_cpu_0
  - readline=7.0=h7b6447c_5
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py37_cpu
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - cffi==1.14.0
    - cloudpickle==1.2.2
    - cycler==0.10.0
    - cython==0.29.15
    - fasteners==0.15
    - future==0.18.2
    - glfw==1.10.1
    - gym==0.15.3
    - imageio==2.6.1
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - monotonic==1.5
    - mujoco-py==2.0.2.9
    - pycparser==2.19
    - pyglet==1.4.10
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - scikit-learn==0.22.1
    - sklearn==0.0
    - tensorboardx==2.0
    - pyyaml==5.3

